feat(signup): add user
RedJanvier/items-manager pull request #5
Opened 2020-10-10 18:13 UTC by Patience250

### What does this PR do?
creating user account
### Description of tasks to be completed
- Create route for registering new user
- Add User model
- Add user controller 
### How to test manually
- Clone the repository or pull from remote and change to "ft-signup" branch
- run `npm install && npm run db:init` 
- run `npm start` and open in your postman `http://localhost:4000/api/users/register`

2020-10-10 21:50 UTC, RedJanvier approved these changes
LGTM

2020-10-11 06:19 UTC, franko-bit approved these changes
Great work Buro

2020-10-11 08:33 UTC, niyodusengaclement requested changes

2020-10-11 08:33 UTC, niyodusengaclement commented on src/controller/users.js
> +    let { email, password, confirm_password } = req.body
U should catch all errors, u can use premises or try and catch

2020-10-11 08:33 UTC, niyodusengaclement commented on src/controller/users.js
> +    if (!email) return res.status(400).send({ error: "Please provide a email" })
Use email pattern or use joi bcz if the user type anything here system will let him in which is not good

2020-10-11 11:42 UTC, Siyubu approved these changes

2020-10-11 14:20 UTC, niyodusengaclement approved these changes

2020-10-11 14:20 UTC, merged